// vue_frontend/src/components/PeopleYouMayKnow.vue
<template>
<div 
v-if = "users.length"
class="p-4 bg-white border border-gray-200 rounded-lg">
        <h3 class="mb-6 text-xl">People you may know</h3>

        <div class="space-y-4">
            <div 
                class="flex items-center justify-between"
                v-for="user in users"
                v-bind:key="user.id"
            >
                <div class="flex items-center space-x-2">
                    <img :src="user.get_avatar" class="w-[40px] rounded-full">
                    
                    <p class="text-xs"><strong>{{ user.name }}</strong></p>
                </div>

                <RouterLink :to="{name: 'profile', params: {id: user.id}}" class="py-2 px-3 bg-purple-600 text-white text-xs rounded-lg">Show</RouterLink>
            </div>
        </div>
    </div>
</template>

<script>
import axios from 'axios'

export default {
    data() {
        return {
            users: []
        }
    },

    mounted() {
        this.getFriendSuggestions()
    },

    methods: {
        getFriendSuggestions() {
            axios
                .get('/api/friends/suggestions/')
                .then(response => {
                    console.log(response.data)

                    this.users = response.data
                })
                .catch(error => {
                    console.log('error', error)
                })
        }
    }
}
</script>

// nextjs_frontend/src/components/PeopleYouMayKnow.tsx
import Link from 'next/link';
import { User } from '@/types';
import apiService from '@/libs/apiService';


export default async function PeopleYouMayKnow() {
  const response = await apiService.get('/api/friends/suggestions/');
  const users: User[] = response.data

  if (!users.length) {
    return null;
  }

  return (
    <div className="p-4 bg-white border border-gray-200 rounded-lg">
      <h3 className="mb-6 text-xl">People you may know</h3>
      <div className="space-y-4">
        {users.map((user) => (
          <div key={user.id} className="flex items-center justify-between">
            <div className="flex items-center space-x-2">
              <img src={user.get_avatar} className="w-[40px] rounded-full" alt={user.name} />
              <p className="text-xs">
                <strong>{user.name}</strong>
              </p>
            </div>
            <Link
              href={`/profile/${user.id}`}
              className="py-2 px-3 bg-purple-600 text-white text-xs rounded-lg hover:bg-purple-700 transition-colors"
            >
              Show
            </Link>
          </div>
        ))}
      </div>
    </div>
  );
}
